# Built with Jekyll 3.2.0

# Setup
title:               Sample Bibliography of Important Fabricated Texts
tagline:             'A Really Important Work'
description:         'This is an important bibliography that was made up as part of a project.'
url:                 'http://www.library.upenn.edu/'
baseurl:             '/sample-bib'

# About/contact
author:
  name:              Penn Libraries
  url:               http://www.library.upenn.edu/
  email:             sample_email@thisisntreal.howdy

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
